### ISSUE TITLE
******** Many errors in the code, and the future of this project? ********

### ISSUE THREAD

**Issue by douglasleer** [Cloudslab/cloudsim#121]
After looking into the code of this project, I found many errors/bugs, just like all the people that have already reported many issues/errors/bugs. 

The errors/bugs definitely affect the correctness of the simulation results. The reported issues are not resolved and the limited pull requests are not accepted.

Besides, the latest update of the project was 2 years ago. It seems that this project lacks too much support from the original authors and the community.

Anyone has any idea on how to make it a reliable toolkit?

**Comment by itconsultore** [comment]
the idea is to make forks and if someone finds an error then work in the
fork, test it, check with the community (a couple of reviewers) and then
apply for a push request.

I check something in 2016 for my thesis, found some errors and improvement,
but one test didn't pass.
I couldn't find the cause, because it was more in deep.


Best wishes,
Francisco

**Comment by AbderrahmanL** [comment]
Go with cloudsim plus the developer supporting it is active, and it's more modular not spaghetti code like cloudsim (with all due respect and appreciation to cloudsim since it's the solid starting point)  so it will be a bit easier to extend and contribute, not to mention that there are many fixes and features added to it .
